### ISSUE TITLE
Can you make the 1.20.1 version

### ISSUE THREAD

**Issue by NyaHan16** [Olexandr43/Smooth-Swapping-1.20.4-Port#3]
First of all, I am sorry for the part that is difficult to read using an interpreter because I am not an English-speaking country

I'm currently using 1.20.1 fabric version using Fabric Compatible mode on Forge in CurseForge, which conflicts with Sophisticated Core mode

I've looked for a number of solutions
Either they couldn't find a solution
The only answer was to use the 1.20.4 version

However, I don't recognize version 1.20.4 in CurseForge and the modes I'm using are not yet 1.20.4 versions

That's why I need version 1.20.1 with errors related to the Sophisticated Core mode and shift click

I hope it's made

**Comment by Olexandr43** [comment]
Hello, firstly, you could use google translate, secondly, [[Forge 1.20] v0.9.2](https://modrinth.com/mod/smooth-swapping/version/cqPaTtap) isn`t working for you?

If you have more questions, feel free to ask)
Hope this helped)

**Comment by NyaHan16** [comment]
This mode does not allow the game to run itself.

Use the Sinytra Connector
If you use the version of Fabric 1.20.1 on that page, the game works, but the error of bouncing when you do Shift Click still exists.
