### ISSUE TITLE
Smooth Swapping doesn't work inside creative inventory

### ISSUE THREAD

**Issue by TheRedstoneShark** [Olexandr43/Smooth-Swapping-1.20.4-Port#6]
Current behavior: Smooth Swapping works great inside containers and in the survival inventory, but in the "Survival Inventory" tab inside the creative inventory, swapping is not smooth.

https://github.com/Olexandr43/Smooth-Swapping-1.20.4-Port/assets/67612434/6c72c180-3cd7-4cf2-8f9c-83a6de3c16d8

**Comment by KollPotato** [comment]
yeah i have the same problem

**Comment by Olexandr43** [comment]
> yeah i have the same problem

you can use this (for 1.21): https://github.com/YoungSoulluoS/Smooth-Swapping-1.20.4-Port/releases

> Current behavior: Smooth Swapping works great inside containers and in the survival inventory, but in the "Survival Inventory" tab inside the creative inventory, swapping is not smooth.
> 
>  catcut_Java_versions.2024.06.29.-.00.17.35.29.DVR.mp4

you can use this (for 1.21): https://github.com/YoungSoulluoS/Smooth-Swapping-1.20.4-Port/releases
